import { useMemo,useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Download, ArrowDown, ArrowUp, CalendarDays, BarChart3, Activity, Info } from 'lucide-react'
import { Link } from '@tanstack/react-router'
import { Button } from '../../components/ui/button'
import { Card, CardContent } from '../../components/ui/card'
import { Badge } from '../../components/ui/badge'
import { Input } from '../../components/ui/input'
import { NativeSelect,NativeSelectOption } from '../../components/ui/native-select'
import { Table, TableHeader,TableHead,TableBody,TableRow,TableCell } from '../../components/ui/table'
import { transforms,breakdowns,ranges,type Settings } from './catalog'
import type { DashboardData } from './snapshot.server'
import type { Locale } from '../../i18n'
import { ContributionChart } from './contribution-chart'
export function Dashboard({data,settings,locale,onChange}:{data:DashboardData;settings:Settings;locale:Locale;onChange:(s:Partial<Settings>)=>void}) {
  const {t}=useTranslation();const [query,setQuery]=useState(''),[view,setView]=useState<'leaves'|'tree'>('leaves'),[descending,setDescending]=useState(true)
  const items=useMemo(()=>{let result=data.items.filter(n=>(view==='tree'||n.leaf)&&(`${n.name} ${n.en}`.toLowerCase().includes(query.toLowerCase())));if(view==='leaves')result=result.sort((a,b)=>((b.contribution??-Infinity)-(a.contribution??-Infinity))*(descending?1:-1));return result},[data,query,view,descending])
  const top=[...data.componentRows].filter(c=>c.value!==null&&c.value>0).sort((a,b)=>(b.value??0)-(a.value??0))[0]
  const fmt=(v:number|null,d=3)=>v===null?'—':v.toFixed(d)
  return <main className="page-shell"><div className="intro-row"><div><p className="eyebrow"><span/> {t('eyebrow')}</p><h1>{t('title')}</h1><p className="intro-subtitle">{t('subtitle')}</p></div><div className="release-panel"><CalendarDays size={17}/><div><span>{t('latest')}</span><strong>{data.latest}</strong><small>{t('published')} · {data.published}</small></div></div></div>
    <div className="metrics-grid">{[{label:'headline',value:fmt(data.headline,2)+'%',note:`${data.month} · ${t(settings.tf)} · ${t('sa')}`,icon:<Activity size={18}/>,primary:true},{label:'core',value:fmt(data.core,2)+'%',note:`${data.month} · ${t(settings.tf)} · ${t('sa')}`,icon:<BarChart3 size={18}/>},{label:'top',value:top?fmt(top.value)+' pp':'—',note:top?.name??t('unavailable'),icon:<ArrowUp size={18}/>},{label:'residual',value:fmt(data.residual)+' pp',note:t('residualHelp'),icon:<Info size={18}/>}].map(c=><Card key={c.label} className={`metric ${c.primary?'metric-primary':''}`}><CardContent><div className="metric-label">{t(c.label)}{c.icon}</div><strong>{c.value}</strong><p>{c.note}</p></CardContent></Card>)}</div>
    <Card className="chart-card"><CardContent><div className="panel-heading"><div><h2>{t('chartTitle')}</h2><p>{t('chartSubtitle')}</p></div><Button variant="outline" asChild><a href={`/data/pce_contrib_${settings.bk}_${settings.tf}.csv`} download><Download size={15}/>{t('download')}</a></Button></div><div className="control-bar"><div className="control-group"><label>{t('rate')}</label><div className="transform-group">{transforms.map(tf=><Button key={tf} variant={settings.tf===tf?'default':'ghost'} size="sm" onClick={()=>onChange({tf})}>{t(tf)}</Button>)}</div></div><div className="control-group"><label htmlFor="breakdown">{t('breakdown')}</label><NativeSelect id="breakdown" value={settings.bk} onChange={e=>onChange({bk:e.target.value as Settings['bk']})}>{breakdowns.map(b=><NativeSelectOption key={b} value={b}>{t(b,{count:data.leafCount})}</NativeSelectOption>)}</NativeSelect></div><div className="control-group"><label htmlFor="history">{t('period')}</label><NativeSelect id="history" value={settings.range} onChange={e=>onChange({range:e.target.value as Settings['range']})}>{ranges.map(r=><NativeSelectOption key={r} value={r}>{t(`range${r}`)}</NativeSelectOption>)}</NativeSelect></div><div className="control-group control-month"><label htmlFor="month">{t('month')}</label><NativeSelect id="month" value={data.month} onChange={e=>onChange({month:e.target.value})}>{[...data.months].reverse().map(m=><NativeSelectOption key={m} value={m}>{m}</NativeSelectOption>)}</NativeSelect></div></div>
      <ContributionChart data={data} onMonth={month=>onChange({month})}/><div className="method-note"><Badge variant="secondary">{t(data.method==='official'?'official':'estimate')}</Badge><span>{settings.tf==='yoy'?t('yoyMethod'):t('sa')}</span><Link to="/$locale/methodology" params={{locale}}>{t('methodology')} →</Link></div></CardContent></Card>
    <Card className="detail-card"><CardContent><div className="panel-heading"><div><h2>{t('detailTitle')} <span className="count-badge">{data.leafCount}</span></h2><p>{t('detailSubtitle')}</p></div><Button variant="outline" asChild><a href={`/data/pce_detail_${settings.tf}.csv`} download><Download size={15}/>{t('detailDownload')}</a></Button></div><div className="detail-controls"><Input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/><label htmlFor="view">{t('display')}</label><NativeSelect id="view" value={view} onChange={e=>setView(e.target.value as 'leaves'|'tree')}><NativeSelectOption value="leaves">{t('leaves')}</NativeSelectOption><NativeSelectOption value="tree">{t('tree')}</NativeSelectOption></NativeSelect><Badge variant="outline">{data.month}</Badge></div><div className="data-table"><Table><TableHeader><TableRow><TableHead>{t('item')}</TableHead><TableHead className="text-right">{t('weight')} %</TableHead><TableHead className="text-right">{t('growth')} %</TableHead><TableHead className="text-right"><button onClick={()=>setDescending(!descending)} disabled={view==='tree'} className="sort-button">{t('contribution')} pp {descending?<ArrowDown size={13}/>:<ArrowUp size={13}/>}</button></TableHead></TableRow></TableHeader><TableBody>{items.map(n=><TableRow key={n.id}><TableCell style={{paddingLeft:view==='tree'?16+(n.level-1)*16:16}}><span className={!n.leaf?'font-semibold':''}>{n.name}</span>{locale!=='en'&&<small className="english-name">{n.en}</small>}</TableCell><TableCell className="text-right tabular-nums">{fmt(n.weight,2)}</TableCell><TableCell className="text-right tabular-nums">{fmt(n.growth,2)}</TableCell><TableCell className={`text-right font-semibold tabular-nums ${(n.contribution??0)>0?'positive':'negative'}`}>{fmt(n.contribution)}</TableCell></TableRow>)}{items.length===0&&<TableRow><TableCell colSpan={4} className="text-center">{t('noResults')}</TableCell></TableRow>}</TableBody></Table></div><p className="table-note">{t('tableNote')}</p><div className="table-total"><span>{t('sum')} <b>{fmt(data.items.filter(n=>n.leaf).reduce((sum,n)=>sum+(n.contribution??0),0))} pp</b></span><span>{t('residual')} <b>{fmt(data.detailResidual)} pp</b></span></div></CardContent></Card><footer className="page-footer"><div>{t('source')}<small>{t('footer')}</small></div><div><a href="/data/pce_data.json" download>{t('json')}</a><a href="/data/validation.json">{t('validation')}</a></div></footer></main>
}
